name: Events exercices

on:
  workflow_dispatch:

jobs:
  print-event:
    runs-on: ubuntu-latest

    steps:
      - name: Print the event that triggered this workflow
        run: |
          echo ${{ github.event_name }}

      - name: Print the current time
        run: |
          echo $(date)

      - name: Create and publish 3 branches, "dev", "staging", "feat/feature-1"
        run : |
          git switch -c dev && git push --set-upstream origin dev
          git switch -c staging && git push --set-upstream origin staging
          git switch -c feat/feature-1 && git push --set-upstream origin feat/feature-1